const PUBLISH_ARTICLE = "PUBLISH_ARTICLE";
const UPDATE_ARTICLE = "UPDATE_ARTICLE";
const DELETE_ARTICLE = "DELETE_ARTICLE";
const VIEW_SUBMITTED_ARTICLE = "VIEW_SUBMITTED_ARTICLE";
const VIEW_ALL_ARTICLES = "VIEW_ALL_ARTICLES";

const VIEW_SELECTED_ARTICLE = "VIEW_SELECTED_ARTICLE";
const FETCH_SELECTED_ARTICLE_DETAILS = "FETCH_SELECTED_ARTICLE_DETAILS";

const FETCH_SELECTED_EDIT_ARTICLE = "FETCH_SELECTED_EDIT_ARTICLE";

const VIEW_EDIT_ARTICLE = "VIEW_EDIT_ARTICLE";

export { PUBLISH_ARTICLE };
export { UPDATE_ARTICLE };
export { DELETE_ARTICLE };
export { VIEW_SUBMITTED_ARTICLE };
export { VIEW_ALL_ARTICLES };

export { VIEW_SELECTED_ARTICLE };
export { FETCH_SELECTED_ARTICLE_DETAILS };
export { FETCH_SELECTED_EDIT_ARTICLE };

export { VIEW_EDIT_ARTICLE };